spring.application.name=monitoring-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle-monitoring
spring.datasource.username=postgres
spring.datasource.password=Pazinapostgres!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update